"""E8 final evidence consolidation and reproducibility validation.

This module does not introduce a new scientific experiment.

It consolidates E4-E7 into one auditable package containing:

- validation of the principal statistical claims;
- publication-ready summary metrics;
- explicit supported claims;
- explicit limitations;
- SHA-256 hashes of the underlying result files;
- a final Markdown research-results report.

The goal is to ensure that the final paper and repository cannot accidentally
overstate what the experiments actually demonstrate.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math

from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class FinalEvidenceConfig:
    """Locations of the final experimental evidence."""

    e4_path: Path = Path(
        "results/e4_100_trials/"
        "three_strategy_statistical_summary.json"
    )

    e5_path: Path = Path(
        "results/e5_robustness/"
        "three_strategy_robustness_summary.json"
    )

    e6_path: Path = Path(
        "results/e6_mechanism/"
        "mechanism_ablation_summary.json"
    )

    e7_path: Path = Path(
        "results/e7_uncertainty_stress/"
        "uncertainty_stress_summary.json"
    )

    output_directory: Path = Path(
        "results/final_evidence"
    )


@dataclass(frozen=True)
class FinalClaim:
    """One evidence-backed final research claim."""

    claim_id: str

    statement: str

    evidence: str


@dataclass(frozen=True)
class FinalPackagePaths:
    """Files generated by E8."""

    summary_json: Path
    metrics_csv: Path
    report_markdown: Path
    reproducibility_manifest: Path


def _load_json(
    path: Path,
) -> dict[str, Any]:
    """Load one required evidence file."""

    if not path.exists():
        raise FileNotFoundError(
            f"Required evidence file does not exist: {path}"
        )

    with path.open(
        "r",
        encoding="utf-8",
    ) as handle:
        payload = json.load(
            handle
        )

    if not isinstance(
        payload,
        dict,
    ):
        raise ValueError(
            f"Evidence file must contain a JSON object: {path}"
        )

    return payload


def _find(
    items: list[dict[str, Any]],
    *,
    field: str,
    value: str,
) -> dict[str, Any]:
    """Find exactly one item by identifier."""

    matches = [
        item
        for item in items
        if item.get(field) == value
    ]

    if len(matches) != 1:
        raise ValueError(
            f"Expected exactly one {field}={value!r}; "
            f"found {len(matches)}."
        )

    return matches[0]


def _require(
    condition: bool,
    message: str,
) -> None:
    """Raise a descriptive error when final evidence is inconsistent."""

    if not condition:
        raise ValueError(
            message
        )


def _ci_excludes_zero_negative(
    metric: dict[str, Any],
) -> bool:
    """Return whether the complete CI lies below zero."""

    return float(
        metric["ci_high"]
    ) < 0.0


def _ci_excludes_zero_positive(
    metric: dict[str, Any],
) -> bool:
    """Return whether the complete CI lies above zero."""

    return float(
        metric["ci_low"]
    ) > 0.0


def _ci_contains_zero(
    metric: dict[str, Any],
) -> bool:
    """Return whether zero lies inside the reported interval."""

    return (
        float(
            metric["ci_low"]
        )
        <= 0.0
        <= float(
            metric["ci_high"]
        )
    )


def _close(
    first: float,
    second: float,
    *,
    tolerance: float = 1e-12,
) -> bool:
    """Numerically compare final deterministic metrics."""

    return math.isclose(
        float(first),
        float(second),
        rel_tol=0.0,
        abs_tol=tolerance,
    )


def validate_evidence(
    *,
    e4: dict[str, Any],
    e5: dict[str, Any],
    e6: dict[str, Any],
    e7: dict[str, Any],
) -> tuple[str, ...]:
    """Validate the scientific claims supported by E4-E7.

    A failure here means the final report must not be generated because one
    of the expected evidence relationships no longer holds.
    """

    checks: list[str] = []

    # ------------------------------------------------------------------
    # E4: stochastic validation within one fixed surgical scene.
    # ------------------------------------------------------------------

    _require(
        int(
            e4["config"]["trial_count"]
        )
        >= 100,
        "E4 must contain at least 100 matched trials.",
    )

    e4_fixed = _find(
        e4["paired_comparisons"],
        field="comparator",
        value="fixed",
    )

    e4_generic = _find(
        e4["paired_comparisons"],
        field="comparator",
        value="generic_active",
    )

    _require(
        _ci_excludes_zero_negative(
            e4_fixed[
                "localisation_error_difference"
            ]
        ),
        "E4 no longer supports lower task-aware localisation error "
        "relative to fixed view.",
    )

    _require(
        _ci_excludes_zero_positive(
            e4_generic[
                "planning_success_rate_difference"
            ]
        ),
        "E4 no longer supports improved planning success relative "
        "to generic active perception.",
    )

    checks.append(
        "E4 stochastic evidence validated."
    )

    # ------------------------------------------------------------------
    # E5: multi-scenario robustness.
    # ------------------------------------------------------------------

    _require(
        len(
            e5["scenarios"]
        )
        >= 10,
        "E5 must contain at least ten surgical-scene variations.",
    )

    e5_fixed = _find(
        e5["paired_comparisons"],
        field="comparator",
        value="fixed",
    )

    e5_generic = _find(
        e5["paired_comparisons"],
        field="comparator",
        value="generic_active",
    )

    for comparison, name in (
        (
            e5_fixed,
            "fixed view",
        ),
        (
            e5_generic,
            "generic active perception",
        ),
    ):
        _require(
            _ci_excludes_zero_negative(
                comparison[
                    "localisation_error_difference"
                ]
            ),
            "E5 no longer supports lower task-aware localisation "
            f"error relative to {name}.",
        )

        _require(
            _ci_excludes_zero_positive(
                comparison[
                    "planning_success_difference"
                ]
            ),
            "E5 no longer supports improved planning success "
            f"relative to {name}.",
        )

        _require(
            _ci_excludes_zero_positive(
                comparison[
                    "safe_navigation_success_difference"
                ]
            ),
            "E5 no longer supports improved safe-navigation "
            f"success relative to {name}.",
        )

    task_e5 = _find(
        e5["summaries"],
        field="strategy",
        value="task_aware_active",
    )

    _require(
        float(
            task_e5[
                "worst_scenario_safe_navigation_rate"
            ]
        )
        >= 0.90,
        "Task-aware worst-scenario safe-navigation rate "
        "fell below the recorded 90% robustness threshold.",
    )

    checks.append(
        "E5 multi-scenario robustness evidence validated."
    )

    # ------------------------------------------------------------------
    # E6: mechanism ablation.
    # ------------------------------------------------------------------

    generic_e6 = _find(
        e6["summaries"],
        field="variant",
        value="generic_baseline",
    )

    alignment_e6 = _find(
        e6["summaries"],
        field="variant",
        value="alignment_only",
    )

    uncertainty_e6 = _find(
        e6["summaries"],
        field="variant",
        value="uncertainty_only",
    )

    full_e6 = _find(
        e6["summaries"],
        field="variant",
        value="full_task_aware",
    )

    for metric_name in (
        "planning_success_rate",
        "safe_navigation_success_rate",
        "localisation_error",
        "predicted_sigma",
    ):
        _require(
            _close(
                generic_e6[
                    metric_name
                ]["mean"],
                uncertainty_e6[
                    metric_name
                ]["mean"],
            ),
            "E6 uncertainty-only no longer matches the generic "
            f"baseline for {metric_name}.",
        )

    _require(
        float(
            alignment_e6[
                "safe_navigation_success_rate"
            ]["mean"]
        )
        > float(
            generic_e6[
                "safe_navigation_success_rate"
            ]["mean"]
        ),
        "E6 no longer supports an alignment-driven "
        "safe-navigation advantage.",
    )

    alignment_comparison = _find(
        e6["full_comparisons"],
        field="comparator",
        value="alignment_only",
    )

    uncertainty_comparison = _find(
        e6["full_comparisons"],
        field="comparator",
        value="uncertainty_only",
    )

    _require(
        _ci_contains_zero(
            alignment_comparison[
                "localisation_error_difference"
            ]
        ),
        "E6 full-versus-alignment localisation CI no longer "
        "contains zero.",
    )

    _require(
        _close(
            full_e6[
                "safe_navigation_success_rate"
            ]["mean"],
            alignment_e6[
                "safe_navigation_success_rate"
            ]["mean"],
        ),
        "E6 full and alignment-only safe-navigation rates "
        "no longer match.",
    )

    _require(
        _ci_excludes_zero_positive(
            uncertainty_comparison[
                "safe_navigation_success_difference"
            ]
        ),
        "E6 no longer supports full task-aware superiority "
        "over uncertainty-only.",
    )

    checks.append(
        "E6 mechanism-ablation evidence validated."
    )

    # ------------------------------------------------------------------
    # E7: uncertainty stress testing.
    # ------------------------------------------------------------------

    for summary in (
        e7["selection_summaries"]
    ):
        _require(
            _close(
                summary[
                    "selection_change_rate"
                ],
                0.0,
            ),
            "E7 contains an uncertainty-only viewpoint change; "
            "the final redundancy claim must be revised.",
        )

        _require(
            _close(
                summary[
                    "mean_sigma_change"
                ],
                0.0,
            ),
            "E7 contains a non-zero selected-sigma change.",
        )

    generic_e7 = _find(
        e7["variant_summaries"],
        field="variant",
        value="generic_baseline",
    )

    uncertainty_e7 = _find(
        e7["variant_summaries"],
        field="variant",
        value="high_uncertainty_only",
    )

    for metric_name in (
        "localisation_error",
        "predicted_sigma",
        "camera_movement",
        "planning_success_rate",
        "safe_navigation_success_rate",
    ):
        _require(
            _close(
                generic_e7[
                    metric_name
                ]["mean"],
                uncertainty_e7[
                    metric_name
                ]["mean"],
            ),
            "E7 high-weight uncertainty-only no longer matches "
            f"generic baseline for {metric_name}.",
        )

    checks.append(
        "E7 uncertainty-stress evidence validated."
    )

    return tuple(
        checks
    )


def _metric_row(
    *,
    stage: str,
    condition: str,
    summary: dict[str, Any],
) -> dict[str, Any]:
    """Convert one experimental summary into a common final table."""

    safe_metric = (
        summary.get(
            "safe_navigation_success_rate"
        )
    )

    return {
        "stage": stage,
        "condition": condition,
        "localisation_error_mm": (
            1000.0
            * float(
                summary[
                    "localisation_error"
                ]["mean"]
            )
        ),
        "predicted_sigma_mm": (
            1000.0
            * float(
                summary[
                    "predicted_sigma"
                ]["mean"]
            )
        ),
        "camera_movement_mm": (
            1000.0
            * float(
                summary[
                    "camera_movement"
                ]["mean"]
            )
        ),
        "planning_success_percent": (
            100.0
            * float(
                summary[
                    "planning_success_rate"
                ]["mean"]
            )
        ),
        "safe_navigation_success_percent": (
            ""
            if safe_metric is None
            else (
                100.0
                * float(
                    safe_metric[
                        "mean"
                    ]
                )
            )
        ),
    }


def build_final_metrics(
    *,
    e5: dict[str, Any],
    e6: dict[str, Any],
    e7: dict[str, Any],
) -> tuple[
    dict[str, Any],
    ...,
]:
    """Build one common publication-ready metrics table."""

    rows: list[
        dict[str, Any]
    ] = []

    for strategy in (
        "fixed",
        "generic_active",
        "task_aware_active",
    ):
        summary = _find(
            e5["summaries"],
            field="strategy",
            value=strategy,
        )

        rows.append(
            _metric_row(
                stage="E5 multi-scenario",
                condition=strategy,
                summary=summary,
            )
        )

    for variant in (
        "generic_baseline",
        "alignment_only",
        "uncertainty_only",
        "full_task_aware",
    ):
        summary = _find(
            e6["summaries"],
            field="variant",
            value=variant,
        )

        rows.append(
            _metric_row(
                stage="E6 mechanism",
                condition=variant,
                summary=summary,
            )
        )

    for variant in (
        "generic_baseline",
        "high_uncertainty_only",
        "alignment_only",
        "full_task_aware",
    ):
        summary = _find(
            e7["variant_summaries"],
            field="variant",
            value=variant,
        )

        rows.append(
            _metric_row(
                stage="E7 uncertainty stress",
                condition=variant,
                summary=summary,
            )
        )

    return tuple(
        rows
    )


def build_final_claims(
    *,
    e5: dict[str, Any],
    e6: dict[str, Any],
    e7: dict[str, Any],
) -> tuple[
    FinalClaim,
    ...,
]:
    """Construct the final evidence-backed scientific claims."""

    task_e5 = _find(
        e5["summaries"],
        field="strategy",
        value="task_aware_active",
    )

    fixed_e5 = _find(
        e5["summaries"],
        field="strategy",
        value="fixed",
    )

    generic_e5 = _find(
        e5["summaries"],
        field="strategy",
        value="generic_active",
    )

    alignment_e6 = _find(
        e6["summaries"],
        field="variant",
        value="alignment_only",
    )

    uncertainty_e6 = _find(
        e6["summaries"],
        field="variant",
        value="uncertainty_only",
    )

    generic_e6 = _find(
        e6["summaries"],
        field="variant",
        value="generic_baseline",
    )

    maximum_tested_weight = max(
        float(
            item["uncertainty_weight"]
        )
        for item
        in e7["selection_summaries"]
    )

    task_safe = (
        100.0
        * float(
            task_e5[
                "safe_navigation_success_rate"
            ]["mean"]
        )
    )

    fixed_safe = (
        100.0
        * float(
            fixed_e5[
                "safe_navigation_success_rate"
            ]["mean"]
        )
    )

    generic_safe = (
        100.0
        * float(
            generic_e5[
                "safe_navigation_success_rate"
            ]["mean"]
        )
    )

    alignment_safe = (
        100.0
        * float(
            alignment_e6[
                "safe_navigation_success_rate"
            ]["mean"]
        )
    )

    uncertainty_safe = (
        100.0
        * float(
            uncertainty_e6[
                "safe_navigation_success_rate"
            ]["mean"]
        )
    )

    generic_e6_safe = (
        100.0
        * float(
            generic_e6[
                "safe_navigation_success_rate"
            ]["mean"]
        )
    )

    return (
        FinalClaim(
            claim_id="C1",
            statement=(
                "Task-aware active perception improved end-to-end "
                "navigation feasibility across the tested multi-scenario "
                "simulation benchmark."
            ),
            evidence=(
                f"E5 safe-navigation success was {task_safe:.1f}% "
                f"for task-aware perception versus {fixed_safe:.1f}% "
                f"for fixed view and {generic_safe:.1f}% for generic "
                "active perception; paired scenario-clustered 95% "
                "confidence intervals for both improvements excluded zero."
            ),
        ),
        FinalClaim(
            claim_id="C2",
            statement=(
                "Task alignment was the dominant viewpoint-selection "
                "mechanism responsible for the observed task-aware benefit."
            ),
            evidence=(
                f"E6 alignment-only achieved {alignment_safe:.1f}% "
                "safe-navigation success, whereas uncertainty-only "
                f"achieved {uncertainty_safe:.1f}% and the generic "
                f"baseline achieved {generic_e6_safe:.1f}%."
            ),
        ),
        FinalClaim(
            claim_id="C3",
            statement=(
                "The explicit uncertainty term did not provide independent "
                "viewpoint-selection information under the tested scoring "
                "and observation models."
            ),
            evidence=(
                "E7 produced zero uncertainty-only viewpoint changes "
                f"for all tested uncertainty weights up to "
                f"{maximum_tested_weight:g} across every scenario/profile "
                "condition."
            ),
        ),
        FinalClaim(
            claim_id="C4",
            statement=(
                "Uncertainty remains operationally important downstream "
                "because perceived localisation uncertainty is propagated "
                "into uncertainty-inflated planning geometry."
            ),
            evidence=(
                "The final architecture separates viewpoint-selection "
                "mechanism evidence from the uncertainty-aware motion-"
                "planning stage and hidden-ground-truth safety evaluation."
            ),
        ),
    )


def final_limitations() -> tuple[
    str,
    ...,
]:
    """Return limitations that must accompany the final claims."""

    return (
        "All reported experiments are simulation-based; no physical "
        "surgical robot or clinical system was evaluated.",
        "The robustness benchmark contains ten engineered surgical-scene "
        "variations rather than ten independent patient anatomies.",
        "The results therefore demonstrate robustness to the tested scene "
        "perturbations, not clinical generalisation.",
        "The experiments do not establish that task-aware perception "
        "reduces collision probability once a valid trajectory already "
        "exists.",
        "The explicit uncertainty term was redundant for viewpoint "
        "selection under the tested model; the principal selection benefit "
        "was attributable to task alignment.",
        "Camera repositioning was substantially greater for task-aware "
        "strategies and should be treated as a real operational trade-off.",
        "The simulated observation model does not capture the full range "
        "of real surgical effects such as tissue deformation, calibration "
        "drift, specularities and dynamic anatomy.",
    )


def _sha256(
    path: Path,
) -> str:
    """Calculate the SHA-256 digest of one evidence file."""

    digest = hashlib.sha256()

    with path.open(
        "rb",
    ) as handle:
        while True:
            block = handle.read(
                1024 * 1024
            )

            if not block:
                break

            digest.update(
                block
            )

    return digest.hexdigest()


def _write_metrics_csv(
    *,
    path: Path,
    rows: tuple[
        dict[str, Any],
        ...,
    ],
) -> None:
    """Write the unified final metrics table."""

    fieldnames = (
        "stage",
        "condition",
        "localisation_error_mm",
        "predicted_sigma_mm",
        "camera_movement_mm",
        "planning_success_percent",
        "safe_navigation_success_percent",
    )

    with path.open(
        "w",
        newline="",
        encoding="utf-8",
    ) as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=fieldnames,
        )

        writer.writeheader()

        for row in rows:
            writer.writerow(
                row
            )


def _markdown_table(
    rows: tuple[
        dict[str, Any],
        ...,
    ],
) -> str:
    """Render the final common metric table."""

    lines = [
        (
            "| Stage | Condition | Localisation error (mm) | "
            "Predicted σ (mm) | Camera movement (mm) | "
            "Planning success | Safe-navigation success |"
        ),
        (
            "|---|---|---:|---:|---:|---:|---:|"
        ),
    ]

    for row in rows:
        safe_value = row[
            "safe_navigation_success_percent"
        ]

        safe_text = (
            "—"
            if safe_value == ""
            else f"{float(safe_value):.1f}%"
        )

        lines.append(
            "| "
            f"{row['stage']} | "
            f"{row['condition']} | "
            f"{float(row['localisation_error_mm']):.3f} | "
            f"{float(row['predicted_sigma_mm']):.3f} | "
            f"{float(row['camera_movement_mm']):.3f} | "
            f"{float(row['planning_success_percent']):.1f}% | "
            f"{safe_text} |"
        )

    return "\n".join(
        lines
    )


def _build_report(
    *,
    checks: tuple[
        str,
        ...,
    ],
    claims: tuple[
        FinalClaim,
        ...,
    ],
    limitations: tuple[
        str,
        ...,
    ],
    metrics: tuple[
        dict[str, Any],
        ...,
    ],
) -> str:
    """Create the final paper-ready evidence report."""

    sections = [
        "# Final Experimental Evidence",
        "",
        (
            "This report consolidates the final end-to-end experimental "
            "evidence for task-aware active perception coupled to "
            "uncertainty-aware surgical motion planning."
        ),
        "",
        "## Evidence validation",
        "",
    ]

    sections.extend(
        f"- {check}"
        for check in checks
    )

    sections.extend(
        [
            "",
            "## Final quantitative summary",
            "",
            _markdown_table(
                metrics
            ),
            "",
            "## Supported claims",
            "",
        ]
    )

    for claim in claims:
        sections.extend(
            [
                f"### {claim.claim_id}",
                "",
                claim.statement,
                "",
                f"Evidence: {claim.evidence}",
                "",
            ]
        )

    sections.extend(
        [
            "## Claims not supported by the evidence",
            "",
            (
                "- The experiments do not support claiming that the "
                "explicit uncertainty term independently improves "
                "viewpoint selection."
            ),
            (
                "- The experiments do not support claiming clinical "
                "safety, clinical effectiveness or patient-level "
                "generalisation."
            ),
            (
                "- The experiments do not support claiming that "
                "task-aware perception reduces collision probability "
                "for trajectories that are already successfully planned."
            ),
            "",
            "## Limitations",
            "",
        ]
    )

    sections.extend(
        f"- {limitation}"
        for limitation in limitations
    )

    sections.extend(
        [
            "",
            "## Final interpretation",
            "",
            (
                "The experimental evidence supports a task-aware active-"
                "perception architecture in which task alignment improves "
                "viewpoint selection, the resulting uncertain anatomical "
                "estimates are propagated into uncertainty-aware planning "
                "geometry, and final trajectories are evaluated against "
                "hidden ground truth. The explicit uncertainty term in "
                "the viewpoint scorer was redundant under the tested "
                "observation model and should not be presented as an "
                "independent source of viewpoint-selection improvement."
            ),
            "",
        ]
    )

    return "\n".join(
        sections
    )


def generate_final_package(
    config: FinalEvidenceConfig
    | None = None,
) -> FinalPackagePaths:
    """Validate all final evidence and generate the E8 package."""

    if config is None:
        config = (
            FinalEvidenceConfig()
        )

    e4 = _load_json(
        config.e4_path
    )

    e5 = _load_json(
        config.e5_path
    )

    e6 = _load_json(
        config.e6_path
    )

    e7 = _load_json(
        config.e7_path
    )

    checks = validate_evidence(
        e4=e4,
        e5=e5,
        e6=e6,
        e7=e7,
    )

    metrics = build_final_metrics(
        e5=e5,
        e6=e6,
        e7=e7,
    )

    claims = build_final_claims(
        e5=e5,
        e6=e6,
        e7=e7,
    )

    limitations = (
        final_limitations()
    )

    config.output_directory.mkdir(
        parents=True,
        exist_ok=True,
    )

    summary_json = (
        config.output_directory
        / "final_results_summary.json"
    )

    metrics_csv = (
        config.output_directory
        / "final_metrics.csv"
    )

    report_markdown = (
        config.output_directory
        / "final_results_report.md"
    )

    reproducibility_manifest = (
        config.output_directory
        / "reproducibility_manifest.json"
    )

    summary_payload = {
        "validation_checks": list(
            checks
        ),
        "claims": [
            asdict(
                claim
            )
            for claim in claims
        ],
        "limitations": list(
            limitations
        ),
        "metrics": list(
            metrics
        ),
    }

    with summary_json.open(
        "w",
        encoding="utf-8",
    ) as handle:
        json.dump(
            summary_payload,
            handle,
            indent=2,
        )

    _write_metrics_csv(
        path=metrics_csv,
        rows=metrics,
    )

    report = _build_report(
        checks=checks,
        claims=claims,
        limitations=limitations,
        metrics=metrics,
    )

    report_markdown.write_text(
        report,
        encoding="utf-8",
    )

    evidence_paths = {
        "E4": config.e4_path,
        "E5": config.e5_path,
        "E6": config.e6_path,
        "E7": config.e7_path,
    }

    manifest = {
        "evidence_files": {
            stage: {
                "path": str(
                    path
                ),
                "sha256": _sha256(
                    path
                ),
            }
            for stage, path
            in evidence_paths.items()
        },
        "generated_files": {
            "summary_json": str(
                summary_json
            ),
            "metrics_csv": str(
                metrics_csv
            ),
            "report_markdown": str(
                report_markdown
            ),
        },
        "validation_checks": list(
            checks
        ),
    }

    with reproducibility_manifest.open(
        "w",
        encoding="utf-8",
    ) as handle:
        json.dump(
            manifest,
            handle,
            indent=2,
        )

    return FinalPackagePaths(
        summary_json=summary_json,
        metrics_csv=metrics_csv,
        report_markdown=report_markdown,
        reproducibility_manifest=(
            reproducibility_manifest
        ),
    )


def main() -> None:
    """Generate the final E8 evidence package."""

    parser = argparse.ArgumentParser(
        description=(
            "Validate E4-E7 evidence and create "
            "the final research-results package."
        )
    )

    parser.add_argument(
        "--output",
        type=Path,
        default=Path(
            "results/final_evidence"
        ),
    )

    args = parser.parse_args()

    config = FinalEvidenceConfig(
        output_directory=args.output
    )

    paths = generate_final_package(
        config
    )

    print()
    print(
        "Final Experimental Evidence Package"
    )
    print(
        "==================================="
    )

    print(
        "E4 evidence: validated"
    )
    print(
        "E5 evidence: validated"
    )
    print(
        "E6 evidence: validated"
    )
    print(
        "E7 evidence: validated"
    )

    print()
    print(
        f"Summary:  {paths.summary_json}"
    )

    print(
        f"Metrics:  {paths.metrics_csv}"
    )

    print(
        f"Report:   {paths.report_markdown}"
    )

    print(
        "Manifest: "
        f"{paths.reproducibility_manifest}"
    )


if __name__ == "__main__":
    main()