"""Secondary and mechanism analysis for the frozen Phase 1 held-out experiment.

IMPORTANT
---------
This module analyses the immutable held-out raw evidence already generated by:

    src.simulation.phase1_final_runner

It DOES NOT rerun simulation and DOES NOT alter the frozen primary analysis.

Frozen protocol SHA-256:

    dc6537d3ff75832ccbe48c9b2690c8e966711b31806076cfbc2721488dbf6361

The primary endpoint remains:

    safe-navigation success

for:

    Full Task-Aware
        versus
    Movement-Budget-Matched Generic

This secondary analysis provides:

- complete eight-strategy descriptive summaries;
- safe-navigation effects for all frozen comparisons;
- planning-success paired permutation tests;
- Holm correction across the complete secondary planning-success family;
- localisation-error paired effects and bootstrap intervals;
- predicted-uncertainty paired effects and bootstrap intervals;
- camera-movement diagnostics;
- collision and safety-violation diagnostics;
- jointly-successful path-cost comparisons;
- task-alignment mechanism summaries.

Repetitions remain nested within held-out scenarios. The inferential unit is
the held-out scenario.

No post-held-out parameter tuning is permitted.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json

from collections import defaultdict
from dataclasses import (
    asdict,
    dataclass,
)
from pathlib import Path

import numpy as np

from src.simulation.phase1_frozen_protocol import (
    BOOTSTRAP_RESAMPLES,
    PERMUTATION_RESAMPLES,
    StrategyId,
    build_frozen_phase1_protocol,
)
from src.simulation.phase1_statistics import (
    FROZEN_PROTOCOL_SHA256,
    StatisticalRecord,
    cluster_bootstrap_mean_difference,
    holm_adjust,
    load_statistical_records,
    paired_success_path_cost_differences,
    sign_flip_permutation_test,
    validate_raw_records,
)


HELD_OUT_ID_MIN = 2000
HELD_OUT_ID_MAX_EXCLUSIVE = 2030

HELD_OUT_SCENARIO_COUNT = 30
HELD_OUT_REPETITIONS = 10
STRATEGY_COUNT = 8

EXPECTED_RAW_RECORD_COUNT = (
    HELD_OUT_SCENARIO_COUNT
    * HELD_OUT_REPETITIONS
    * STRATEGY_COUNT
)


@dataclass(frozen=True)
class SecondaryRecord:
    """Raw quantities required for secondary analysis."""

    scenario_id: int

    repetition: int

    strategy: str

    camera_movement: float

    mean_localisation_error: float

    mean_predicted_sigma: float

    task_relevance: float | None

    task_alignment: float | None

    planning_success: bool

    collision_against_truth: bool

    safety_violation_against_truth: bool

    safe_navigation_success: bool

    path_cost: float


@dataclass(frozen=True)
class StrategySummary:
    """Held-out descriptive summary for one strategy."""

    strategy: str

    scenario_count: int

    trial_count: int

    safe_navigation_rate: float

    planning_success_rate: float

    collision_rate: float

    safety_violation_rate: float

    mean_camera_movement_mm: float

    mean_localisation_error_mm: float

    mean_predicted_sigma_mm: float

    mean_task_alignment: float | None

    mean_task_relevance: float | None


@dataclass(frozen=True)
class ComparisonSummary:
    """One frozen Task-Aware comparison."""

    comparison_name: str

    comparison_role: str

    task_strategy: str

    comparator_strategy: str

    scenario_count: int

    task_safe_navigation_rate: float

    comparator_safe_navigation_rate: float

    safe_navigation_effect_pp: float

    task_planning_success_rate: float

    comparator_planning_success_rate: float

    planning_success_effect_pp: float

    planning_permutation_p_raw: float

    planning_permutation_p_holm: float

    localisation_effect_mm: float

    localisation_ci_lower_mm: float

    localisation_ci_upper_mm: float

    sigma_effect_mm: float

    sigma_ci_lower_mm: float

    sigma_ci_upper_mm: float

    task_camera_movement_mm: float

    comparator_camera_movement_mm: float

    movement_effect_mm: float

    movement_mismatch_fraction_of_task: float

    collision_effect_pp: float

    safety_violation_effect_pp: float

    jointly_successful_path_scenario_count: int

    path_cost_effect: float | None

    path_cost_ci_lower: float | None

    path_cost_ci_upper: float | None


@dataclass(frozen=True)
class Phase1SecondaryAnalysis:
    """Complete secondary held-out analysis."""

    protocol_sha256: str

    raw_results_sha256: str

    raw_record_count: int

    scenario_count: int

    repetitions_per_scenario: int

    strategy_count: int

    planning_secondary_family_size: int

    permutation_resamples: int

    bootstrap_resamples: int

    strategy_summaries: tuple[
        StrategySummary,
        ...,
    ]

    comparisons: tuple[
        ComparisonSummary,
        ...,
    ]

    interpretation_note: str


def _parse_bool(
    value: object,
) -> bool:
    """Parse a CSV boolean strictly."""

    if isinstance(
        value,
        bool,
    ):
        return value

    text = str(
        value
    ).strip().lower()

    if text in (
        "true",
        "1",
    ):
        return True

    if text in (
        "false",
        "0",
    ):
        return False

    raise ValueError(
        f"Invalid boolean value: {value!r}"
    )


def _optional_float(
    value: object,
) -> float | None:
    """Parse optional finite float fields."""

    if value is None:
        return None

    text = str(
        value
    ).strip()

    if text.lower() in (
        "",
        "none",
        "null",
    ):
        return None

    number = float(
        text
    )

    if not np.isfinite(
        number
    ):
        raise ValueError(
            "Optional diagnostic value must be finite when present."
        )

    return float(
        number
    )


def file_sha256(
    path: str | Path,
) -> str:
    """Return SHA-256 digest of the immutable raw held-out CSV."""

    path = Path(
        path
    )

    digest = hashlib.sha256()

    with path.open(
        "rb"
    ) as handle:
        while True:
            block = handle.read(
                1024
                * 1024
            )

            if not block:
                break

            digest.update(
                block
            )

    return digest.hexdigest()


def load_secondary_records(
    path: str | Path,
) -> tuple[
    SecondaryRecord,
    ...,
]:
    """Load all secondary-analysis quantities from the held-out CSV."""

    path = Path(
        path
    )

    if not path.exists():
        raise FileNotFoundError(
            f"Held-out evidence not found: {path}"
        )

    records: list[
        SecondaryRecord
    ] = []

    with path.open(
        "r",
        newline="",
        encoding="utf-8",
    ) as handle:
        reader = csv.DictReader(
            handle
        )

        required = {
            "scenario_id",
            "repetition",
            "strategy",
            "camera_movement",
            "mean_localisation_error",
            "mean_predicted_sigma",
            "task_relevance",
            "task_alignment",
            "planning_success",
            "collision_against_truth",
            "safety_violation_against_truth",
            "safe_navigation_success",
            "path_cost",
        }

        observed = set(
            reader.fieldnames
            or []
        )

        missing = (
            required
            - observed
        )

        if missing:
            raise ValueError(
                "Held-out CSV is missing required columns: "
                f"{sorted(missing)}"
            )

        for row in reader:
            records.append(
                SecondaryRecord(
                    scenario_id=int(
                        row[
                            "scenario_id"
                        ]
                    ),
                    repetition=int(
                        row[
                            "repetition"
                        ]
                    ),
                    strategy=str(
                        row[
                            "strategy"
                        ]
                    ),
                    camera_movement=float(
                        row[
                            "camera_movement"
                        ]
                    ),
                    mean_localisation_error=float(
                        row[
                            "mean_localisation_error"
                        ]
                    ),
                    mean_predicted_sigma=float(
                        row[
                            "mean_predicted_sigma"
                        ]
                    ),
                    task_relevance=(
                        _optional_float(
                            row[
                                "task_relevance"
                            ]
                        )
                    ),
                    task_alignment=(
                        _optional_float(
                            row[
                                "task_alignment"
                            ]
                        )
                    ),
                    planning_success=(
                        _parse_bool(
                            row[
                                "planning_success"
                            ]
                        )
                    ),
                    collision_against_truth=(
                        _parse_bool(
                            row[
                                "collision_against_truth"
                            ]
                        )
                    ),
                    safety_violation_against_truth=(
                        _parse_bool(
                            row[
                                "safety_violation_against_truth"
                            ]
                        )
                    ),
                    safe_navigation_success=(
                        _parse_bool(
                            row[
                                "safe_navigation_success"
                            ]
                        )
                    ),
                    path_cost=float(
                        row[
                            "path_cost"
                        ]
                    ),
                )
            )

    if not records:
        raise ValueError(
            "Held-out CSV contains no records."
        )

    return tuple(
        records
    )


def validate_frozen_held_out_shape(
    records: tuple[
        SecondaryRecord,
        ...,
    ],
) -> None:
    """Verify that the final 30 x 10 x 8 experiment is complete."""

    if len(
        records
    ) != EXPECTED_RAW_RECORD_COUNT:
        raise ValueError(
            "Frozen held-out record count is incorrect. "
            f"Expected {EXPECTED_RAW_RECORD_COUNT}, "
            f"received {len(records)}."
        )

    scenario_ids = {
        record.scenario_id
        for record
        in records
    }

    expected_scenario_ids = set(
        range(
            HELD_OUT_ID_MIN,
            HELD_OUT_ID_MAX_EXCLUSIVE,
        )
    )

    if (
        scenario_ids
        != expected_scenario_ids
    ):
        raise ValueError(
            "Held-out scenario IDs do not match the frozen split."
        )

    expected_strategies = {
        strategy.value
        for strategy
        in StrategyId
    }

    grouped: dict[
        tuple[
            int,
            int,
        ],
        list[
            SecondaryRecord
        ],
    ] = defaultdict(
        list
    )

    for record in records:
        grouped[
            (
                record.scenario_id,
                record.repetition,
            )
        ].append(
            record
        )

        finite_values = (
            record.camera_movement,
            record.mean_localisation_error,
            record.mean_predicted_sigma,
        )

        if not all(
            np.isfinite(
                value
            )
            for value
            in finite_values
        ):
            raise ValueError(
                "Non-finite perception or movement result detected."
            )

        if (
            record.planning_success
            and not np.isfinite(
                record.path_cost
            )
        ):
            raise ValueError(
                "Successful planning record has non-finite path cost."
            )

        if (
            not record.planning_success
            and np.isnan(
                record.path_cost
            )
        ):
            raise ValueError(
                "Failed planning record contains NaN path cost."
            )

    if len(
        grouped
    ) != (
        HELD_OUT_SCENARIO_COUNT
        * HELD_OUT_REPETITIONS
    ):
        raise ValueError(
            "Frozen trial count is incorrect."
        )

    for (
        scenario_id,
        repetition,
    ), trial_records in grouped.items():

        if not (
            0
            <= repetition
            < HELD_OUT_REPETITIONS
        ):
            raise ValueError(
                "Unexpected held-out repetition index."
            )

        strategies = {
            record.strategy
            for record
            in trial_records
        }

        if (
            strategies
            != expected_strategies
        ):
            raise ValueError(
                "Incomplete strategy family for "
                f"scenario={scenario_id}, "
                f"repetition={repetition}."
            )


def _strategy_records(
    records: tuple[
        SecondaryRecord,
        ...,
    ],
    strategy: str,
) -> tuple[
    SecondaryRecord,
    ...,
]:
    """Return records for one strategy."""

    selected = tuple(
        record
        for record
        in records
        if record.strategy
        == strategy
    )

    if not selected:
        raise ValueError(
            f"No records found for strategy {strategy!r}."
        )

    return selected


def _scenario_boolean_rate(
    records: tuple[
        SecondaryRecord,
        ...,
    ],
    *,
    strategy: str,
    attribute: str,
) -> dict[
    int,
    float,
]:
    """Aggregate one Boolean endpoint within each scenario."""

    grouped: dict[
        int,
        list[
            float
        ],
    ] = defaultdict(
        list
    )

    for record in _strategy_records(
        records,
        strategy,
    ):
        grouped[
            record.scenario_id
        ].append(
            float(
                bool(
                    getattr(
                        record,
                        attribute,
                    )
                )
            )
        )

    return {
        scenario_id: float(
            np.mean(
                values
            )
        )
        for scenario_id, values
        in grouped.items()
    }


def _scenario_numeric_mean(
    records: tuple[
        SecondaryRecord,
        ...,
    ],
    *,
    strategy: str,
    attribute: str,
) -> dict[
    int,
    float,
]:
    """Aggregate one continuous metric within each scenario."""

    grouped: dict[
        int,
        list[
            float
        ],
    ] = defaultdict(
        list
    )

    for record in _strategy_records(
        records,
        strategy,
    ):
        value = float(
            getattr(
                record,
                attribute,
            )
        )

        if not np.isfinite(
            value
        ):
            raise ValueError(
                f"Non-finite {attribute} for strategy {strategy}."
            )

        grouped[
            record.scenario_id
        ].append(
            value
        )

    return {
        scenario_id: float(
            np.mean(
                values
            )
        )
        for scenario_id, values
        in grouped.items()
    }


def _scenario_optional_numeric_mean(
    records: tuple[
        SecondaryRecord,
        ...,
    ],
    *,
    strategy: str,
    attribute: str,
) -> dict[
    int,
    float,
]:
    """Aggregate an optional diagnostic where values exist."""

    grouped: dict[
        int,
        list[
            float
        ],
    ] = defaultdict(
        list
    )

    for record in _strategy_records(
        records,
        strategy,
    ):
        value = getattr(
            record,
            attribute,
        )

        if value is None:
            continue

        grouped[
            record.scenario_id
        ].append(
            float(
                value
            )
        )

    return {
        scenario_id: float(
            np.mean(
                values
            )
        )
        for scenario_id, values
        in grouped.items()
        if values
    }


def _paired_differences(
    task: dict[
        int,
        float,
    ],
    comparator: dict[
        int,
        float,
    ],
) -> np.ndarray:
    """Return scenario-level Task minus Comparator differences."""

    if set(
        task
    ) != set(
        comparator
    ):
        raise ValueError(
            "Paired scenario sets differ."
        )

    if not task:
        raise ValueError(
            "No paired scenarios available."
        )

    return np.asarray(
        [
            task[
                scenario_id
            ]
            - comparator[
                scenario_id
            ]
            for scenario_id
            in sorted(
                task
            )
        ],
        dtype=float,
    )


def _mean_scenario_value(
    values: dict[
        int,
        float,
    ],
) -> float:
    """Return equal-weight scenario mean."""

    if not values:
        raise ValueError(
            "Scenario values must not be empty."
        )

    return float(
        np.mean(
            np.asarray(
                tuple(
                    values.values()
                ),
                dtype=float,
            )
        )
    )


def _bootstrap_ci(
    differences: np.ndarray,
    *,
    resamples: int,
    seed: int,
) -> tuple[
    float,
    float,
]:
    """Return frozen 95% scenario bootstrap interval."""

    result = (
        cluster_bootstrap_mean_difference(
            differences,
            resamples=resamples,
            seed=seed,
            confidence_level=0.95,
        )
    )

    return (
        float(
            result.lower
        ),
        float(
            result.upper
        ),
    )


def build_strategy_summaries(
    records: tuple[
        SecondaryRecord,
        ...,
    ],
) -> tuple[
    StrategySummary,
    ...,
]:
    """Build complete eight-strategy descriptive summaries."""

    summaries: list[
        StrategySummary
    ] = []

    for strategy_id in StrategyId:
        strategy = (
            strategy_id.value
        )

        strategy_records = (
            _strategy_records(
                records,
                strategy,
            )
        )

        safe = (
            _scenario_boolean_rate(
                records,
                strategy=strategy,
                attribute=(
                    "safe_navigation_success"
                ),
            )
        )

        planning = (
            _scenario_boolean_rate(
                records,
                strategy=strategy,
                attribute=(
                    "planning_success"
                ),
            )
        )

        collision = (
            _scenario_boolean_rate(
                records,
                strategy=strategy,
                attribute=(
                    "collision_against_truth"
                ),
            )
        )

        violation = (
            _scenario_boolean_rate(
                records,
                strategy=strategy,
                attribute=(
                    "safety_violation_against_truth"
                ),
            )
        )

        movement = (
            _scenario_numeric_mean(
                records,
                strategy=strategy,
                attribute=(
                    "camera_movement"
                ),
            )
        )

        localisation = (
            _scenario_numeric_mean(
                records,
                strategy=strategy,
                attribute=(
                    "mean_localisation_error"
                ),
            )
        )

        sigma = (
            _scenario_numeric_mean(
                records,
                strategy=strategy,
                attribute=(
                    "mean_predicted_sigma"
                ),
            )
        )

        alignment = (
            _scenario_optional_numeric_mean(
                records,
                strategy=strategy,
                attribute=(
                    "task_alignment"
                ),
            )
        )

        relevance = (
            _scenario_optional_numeric_mean(
                records,
                strategy=strategy,
                attribute=(
                    "task_relevance"
                ),
            )
        )

        summaries.append(
            StrategySummary(
                strategy=strategy,
                scenario_count=len(
                    safe
                ),
                trial_count=len(
                    strategy_records
                ),
                safe_navigation_rate=(
                    _mean_scenario_value(
                        safe
                    )
                ),
                planning_success_rate=(
                    _mean_scenario_value(
                        planning
                    )
                ),
                collision_rate=(
                    _mean_scenario_value(
                        collision
                    )
                ),
                safety_violation_rate=(
                    _mean_scenario_value(
                        violation
                    )
                ),
                mean_camera_movement_mm=(
                    _mean_scenario_value(
                        movement
                    )
                    * 1000.0
                ),
                mean_localisation_error_mm=(
                    _mean_scenario_value(
                        localisation
                    )
                    * 1000.0
                ),
                mean_predicted_sigma_mm=(
                    _mean_scenario_value(
                        sigma
                    )
                    * 1000.0
                ),
                mean_task_alignment=(
                    _mean_scenario_value(
                        alignment
                    )
                    if alignment
                    else None
                ),
                mean_task_relevance=(
                    _mean_scenario_value(
                        relevance
                    )
                    if relevance
                    else None
                ),
            )
        )

    return tuple(
        summaries
    )


def build_comparison_summaries(
    *,
    secondary_records: tuple[
        SecondaryRecord,
        ...,
    ],
    statistical_records: tuple[
        StatisticalRecord,
        ...,
    ],
    permutation_resamples: int = (
        PERMUTATION_RESAMPLES
    ),
    bootstrap_resamples: int = (
        BOOTSTRAP_RESAMPLES
    ),
) -> tuple[
    ComparisonSummary,
    ...,
]:
    """Evaluate every comparison frozen before held-out execution."""

    if permutation_resamples <= 0:
        raise ValueError(
            "permutation_resamples must be positive."
        )

    if bootstrap_resamples <= 0:
        raise ValueError(
            "bootstrap_resamples must be positive."
        )

    protocol = (
        build_frozen_phase1_protocol()
    )

    temporary: list[
        dict
    ] = []

    planning_raw_p_values: list[
        float
    ] = []

    for index, comparison in enumerate(
        protocol.comparisons
    ):
        task_strategy = (
            comparison
            .strategy_a
            .value
        )

        comparator_strategy = (
            comparison
            .strategy_b
            .value
        )

        task_safe = (
            _scenario_boolean_rate(
                secondary_records,
                strategy=task_strategy,
                attribute=(
                    "safe_navigation_success"
                ),
            )
        )

        comparator_safe = (
            _scenario_boolean_rate(
                secondary_records,
                strategy=(
                    comparator_strategy
                ),
                attribute=(
                    "safe_navigation_success"
                ),
            )
        )

        safe_difference = (
            _paired_differences(
                task_safe,
                comparator_safe,
            )
        )

        task_plan = (
            _scenario_boolean_rate(
                secondary_records,
                strategy=task_strategy,
                attribute=(
                    "planning_success"
                ),
            )
        )

        comparator_plan = (
            _scenario_boolean_rate(
                secondary_records,
                strategy=(
                    comparator_strategy
                ),
                attribute=(
                    "planning_success"
                ),
            )
        )

        planning_difference = (
            _paired_differences(
                task_plan,
                comparator_plan,
            )
        )

        planning_test = (
            sign_flip_permutation_test(
                planning_difference,
                resamples=(
                    permutation_resamples
                ),
                seed=(
                    protocol
                    .seeds
                    .permutation_seed
                    + index
                ),
            )
        )

        planning_raw_p_values.append(
            float(
                planning_test
                .p_value_two_sided
            )
        )

        task_localisation = (
            _scenario_numeric_mean(
                secondary_records,
                strategy=task_strategy,
                attribute=(
                    "mean_localisation_error"
                ),
            )
        )

        comparator_localisation = (
            _scenario_numeric_mean(
                secondary_records,
                strategy=(
                    comparator_strategy
                ),
                attribute=(
                    "mean_localisation_error"
                ),
            )
        )

        localisation_difference = (
            _paired_differences(
                task_localisation,
                comparator_localisation,
            )
        )

        localisation_ci = (
            _bootstrap_ci(
                localisation_difference,
                resamples=(
                    bootstrap_resamples
                ),
                seed=(
                    protocol
                    .seeds
                    .bootstrap_seed
                    + index
                    * 10
                    + 1
                ),
            )
        )

        task_sigma = (
            _scenario_numeric_mean(
                secondary_records,
                strategy=task_strategy,
                attribute=(
                    "mean_predicted_sigma"
                ),
            )
        )

        comparator_sigma = (
            _scenario_numeric_mean(
                secondary_records,
                strategy=(
                    comparator_strategy
                ),
                attribute=(
                    "mean_predicted_sigma"
                ),
            )
        )

        sigma_difference = (
            _paired_differences(
                task_sigma,
                comparator_sigma,
            )
        )

        sigma_ci = (
            _bootstrap_ci(
                sigma_difference,
                resamples=(
                    bootstrap_resamples
                ),
                seed=(
                    protocol
                    .seeds
                    .bootstrap_seed
                    + index
                    * 10
                    + 2
                ),
            )
        )

        task_movement = (
            _scenario_numeric_mean(
                secondary_records,
                strategy=task_strategy,
                attribute=(
                    "camera_movement"
                ),
            )
        )

        comparator_movement = (
            _scenario_numeric_mean(
                secondary_records,
                strategy=(
                    comparator_strategy
                ),
                attribute=(
                    "camera_movement"
                ),
            )
        )

        movement_difference = (
            _paired_differences(
                task_movement,
                comparator_movement,
            )
        )

        task_movement_mean = (
            _mean_scenario_value(
                task_movement
            )
        )

        comparator_movement_mean = (
            _mean_scenario_value(
                comparator_movement
            )
        )

        if (
            task_movement_mean
            > 1e-12
        ):
            movement_mismatch = (
                abs(
                    task_movement_mean
                    - comparator_movement_mean
                )
                / task_movement_mean
            )

        else:
            movement_mismatch = float(
                "inf"
            )

        task_collision = (
            _scenario_boolean_rate(
                secondary_records,
                strategy=task_strategy,
                attribute=(
                    "collision_against_truth"
                ),
            )
        )

        comparator_collision = (
            _scenario_boolean_rate(
                secondary_records,
                strategy=(
                    comparator_strategy
                ),
                attribute=(
                    "collision_against_truth"
                ),
            )
        )

        collision_difference = (
            _paired_differences(
                task_collision,
                comparator_collision,
            )
        )

        task_violation = (
            _scenario_boolean_rate(
                secondary_records,
                strategy=task_strategy,
                attribute=(
                    "safety_violation_against_truth"
                ),
            )
        )

        comparator_violation = (
            _scenario_boolean_rate(
                secondary_records,
                strategy=(
                    comparator_strategy
                ),
                attribute=(
                    "safety_violation_against_truth"
                ),
            )
        )

        violation_difference = (
            _paired_differences(
                task_violation,
                comparator_violation,
            )
        )

        path_effects = (
            paired_success_path_cost_differences(
                statistical_records,
                task_strategy=(
                    task_strategy
                ),
                comparator_strategy=(
                    comparator_strategy
                ),
            )
        )

        if path_effects:
            path_differences = np.asarray(
                [
                    path_effects[
                        scenario_id
                    ]
                    for scenario_id
                    in sorted(
                        path_effects
                    )
                ],
                dtype=float,
            )

            path_ci = (
                _bootstrap_ci(
                    path_differences,
                    resamples=(
                        bootstrap_resamples
                    ),
                    seed=(
                        protocol
                        .seeds
                        .bootstrap_seed
                        + index
                        * 10
                        + 3
                    ),
                )
            )

            path_effect = float(
                np.mean(
                    path_differences
                )
            )

            path_ci_lower = float(
                path_ci[
                    0
                ]
            )

            path_ci_upper = float(
                path_ci[
                    1
                ]
            )

        else:
            path_effect = None
            path_ci_lower = None
            path_ci_upper = None

        temporary.append(
            {
                "comparison_name": (
                    comparison.name
                ),
                "comparison_role": (
                    comparison.role
                ),
                "task_strategy": (
                    task_strategy
                ),
                "comparator_strategy": (
                    comparator_strategy
                ),
                "scenario_count": len(
                    task_safe
                ),
                "task_safe_navigation_rate": (
                    _mean_scenario_value(
                        task_safe
                    )
                ),
                "comparator_safe_navigation_rate": (
                    _mean_scenario_value(
                        comparator_safe
                    )
                ),
                "safe_navigation_effect_pp": (
                    float(
                        np.mean(
                            safe_difference
                        )
                    )
                    * 100.0
                ),
                "task_planning_success_rate": (
                    _mean_scenario_value(
                        task_plan
                    )
                ),
                "comparator_planning_success_rate": (
                    _mean_scenario_value(
                        comparator_plan
                    )
                ),
                "planning_success_effect_pp": (
                    float(
                        np.mean(
                            planning_difference
                        )
                    )
                    * 100.0
                ),
                "planning_permutation_p_raw": (
                    float(
                        planning_test
                        .p_value_two_sided
                    )
                ),
                "localisation_effect_mm": (
                    float(
                        np.mean(
                            localisation_difference
                        )
                    )
                    * 1000.0
                ),
                "localisation_ci_lower_mm": (
                    float(
                        localisation_ci[
                            0
                        ]
                    )
                    * 1000.0
                ),
                "localisation_ci_upper_mm": (
                    float(
                        localisation_ci[
                            1
                        ]
                    )
                    * 1000.0
                ),
                "sigma_effect_mm": (
                    float(
                        np.mean(
                            sigma_difference
                        )
                    )
                    * 1000.0
                ),
                "sigma_ci_lower_mm": (
                    float(
                        sigma_ci[
                            0
                        ]
                    )
                    * 1000.0
                ),
                "sigma_ci_upper_mm": (
                    float(
                        sigma_ci[
                            1
                        ]
                    )
                    * 1000.0
                ),
                "task_camera_movement_mm": (
                    task_movement_mean
                    * 1000.0
                ),
                "comparator_camera_movement_mm": (
                    comparator_movement_mean
                    * 1000.0
                ),
                "movement_effect_mm": (
                    float(
                        np.mean(
                            movement_difference
                        )
                    )
                    * 1000.0
                ),
                "movement_mismatch_fraction_of_task": (
                    float(
                        movement_mismatch
                    )
                ),
                "collision_effect_pp": (
                    float(
                        np.mean(
                            collision_difference
                        )
                    )
                    * 100.0
                ),
                "safety_violation_effect_pp": (
                    float(
                        np.mean(
                            violation_difference
                        )
                    )
                    * 100.0
                ),
                "jointly_successful_path_scenario_count": (
                    len(
                        path_effects
                    )
                ),
                "path_cost_effect": (
                    path_effect
                ),
                "path_cost_ci_lower": (
                    path_ci_lower
                ),
                "path_cost_ci_upper": (
                    path_ci_upper
                ),
            }
        )

    # Planning success is a frozen secondary endpoint.
    #
    # All planning-success inferential p-values across all pre-specified
    # comparisons therefore form one Holm-corrected secondary family.
    adjusted = (
        holm_adjust(
            tuple(
                planning_raw_p_values
            )
        )
    )

    summaries: list[
        ComparisonSummary
    ] = []

    for payload, adjusted_p in zip(
        temporary,
        adjusted,
    ):
        summaries.append(
            ComparisonSummary(
                **payload,
                planning_permutation_p_holm=float(
                    adjusted_p
                ),
            )
        )

    return tuple(
        summaries
    )


def run_secondary_analysis(
    *,
    raw_path: str | Path,
    permutation_resamples: int = (
        PERMUTATION_RESAMPLES
    ),
    bootstrap_resamples: int = (
        BOOTSTRAP_RESAMPLES
    ),
    require_frozen_shape: bool = True,
) -> Phase1SecondaryAnalysis:
    """Run the complete pre-specified secondary analysis."""

    raw_path = Path(
        raw_path
    )

    # Reuse primary-analysis record validation. This checks strategy-family
    # completeness, paired seeds, duplicates and conditional path-cost rules.
    statistical_records = (
        load_statistical_records(
            raw_path
        )
    )

    validate_raw_records(
        statistical_records
    )

    secondary_records = (
        load_secondary_records(
            raw_path
        )
    )

    if (
        len(
            statistical_records
        )
        != len(
            secondary_records
        )
    ):
        raise ValueError(
            "Primary and secondary loaders returned different "
            "record counts."
        )

    if require_frozen_shape:
        validate_frozen_held_out_shape(
            secondary_records
        )

    strategies = (
        build_strategy_summaries(
            secondary_records
        )
    )

    comparisons = (
        build_comparison_summaries(
            secondary_records=(
                secondary_records
            ),
            statistical_records=(
                statistical_records
            ),
            permutation_resamples=(
                permutation_resamples
            ),
            bootstrap_resamples=(
                bootstrap_resamples
            ),
        )
    )

    scenario_ids = {
        record.scenario_id
        for record
        in secondary_records
    }

    repetitions = {
        record.repetition
        for record
        in secondary_records
    }

    return Phase1SecondaryAnalysis(
        protocol_sha256=(
            FROZEN_PROTOCOL_SHA256
        ),
        raw_results_sha256=(
            file_sha256(
                raw_path
            )
        ),
        raw_record_count=len(
            secondary_records
        ),
        scenario_count=len(
            scenario_ids
        ),
        repetitions_per_scenario=len(
            repetitions
        ),
        strategy_count=len(
            strategies
        ),
        planning_secondary_family_size=len(
            comparisons
        ),
        permutation_resamples=int(
            permutation_resamples
        ),
        bootstrap_resamples=int(
            bootstrap_resamples
        ),
        strategy_summaries=(
            strategies
        ),
        comparisons=(
            comparisons
        ),
        interpretation_note=(
            "Secondary analyses do not replace the frozen primary "
            "conclusion. Positive Task-minus-Comparator values favour "
            "Task-Aware for success outcomes; negative values favour "
            "Task-Aware for localisation error, predicted sigma, "
            "camera movement, collision, safety violation and path cost. "
            "Planning-success p-values are Holm corrected across the "
            "complete pre-specified comparison family."
        ),
    )


def save_secondary_analysis(
    analysis: Phase1SecondaryAnalysis,
    *,
    output_path: str | Path,
    overwrite: bool = False,
) -> Path:
    """Save secondary evidence without changing raw results."""

    output_path = Path(
        output_path
    )

    if (
        output_path.exists()
        and not overwrite
    ):
        raise FileExistsError(
            "Refusing to overwrite existing secondary evidence: "
            f"{output_path}"
        )

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    with output_path.open(
        "w",
        encoding="utf-8",
    ) as handle:
        json.dump(
            asdict(
                analysis
            ),
            handle,
            indent=2,
            allow_nan=False,
        )

    return output_path


def _format_optional(
    value: float | None,
    *,
    decimals: int = 3,
) -> str:
    """Format an optional number."""

    if value is None:
        return "n/a"

    return (
        f"{value:.{decimals}f}"
    )


def print_secondary_analysis(
    analysis: Phase1SecondaryAnalysis,
) -> None:
    """Print the complete mechanism-analysis summary."""

    print()

    print(
        "Phase 1 Held-Out Secondary & Ablation Analysis"
    )

    print(
        "================================================"
    )

    print()

    print(
        f"Raw records:              "
        f"{analysis.raw_record_count}"
    )

    print(
        f"Held-out scenarios:       "
        f"{analysis.scenario_count}"
    )

    print(
        f"Repetitions/scenario:     "
        f"{analysis.repetitions_per_scenario}"
    )

    print(
        f"Strategies:               "
        f"{analysis.strategy_count}"
    )

    print()

    print(
        "Raw evidence SHA-256:"
    )

    print(
        f"  {analysis.raw_results_sha256}"
    )

    print()

    print(
        "EIGHT-STRATEGY HELD-OUT SUMMARY"
    )

    print(
        "Strategy                     "
        "Safe%   Plan%   Move(mm)  Error(mm) Sigma(mm) Coll%  Viol%  Align"
    )

    print(
        "-" * 100
    )

    for summary in (
        analysis
        .strategy_summaries
    ):
        alignment = (
            "   n/a"
            if summary.mean_task_alignment
            is None
            else (
                f"{summary.mean_task_alignment:6.3f}"
            )
        )

        print(
            f"{summary.strategy:28s} "
            f"{summary.safe_navigation_rate * 100.0:6.2f} "
            f"{summary.planning_success_rate * 100.0:7.2f} "
            f"{summary.mean_camera_movement_mm:9.3f} "
            f"{summary.mean_localisation_error_mm:10.3f} "
            f"{summary.mean_predicted_sigma_mm:9.3f} "
            f"{summary.collision_rate * 100.0:6.2f} "
            f"{summary.safety_violation_rate * 100.0:6.2f} "
            f"{alignment}"
        )

    print()

    print(
        "FROZEN COMPARISONS"
    )

    print(
        "Effects are Full Task-Aware minus Comparator."
    )

    print(
        "For success outcomes: positive favours Task-Aware."
    )

    print(
        "For error/sigma/movement/path cost: negative favours Task-Aware."
    )

    print()

    print(
        "Comparison                              "
        "SafeΔ(pp) PlanΔ(pp) Holm-p   "
        "ErrΔ(mm) SigmaΔ(mm) MoveΔ(mm) PathΔ"
    )

    print(
        "-" * 110
    )

    for comparison in (
        analysis.comparisons
    ):
        path_text = (
            "n/a"
            if comparison.path_cost_effect
            is None
            else (
                f"{comparison.path_cost_effect:+.3f}"
            )
        )

        print(
            f"{comparison.comparison_name:38s} "
            f"{comparison.safe_navigation_effect_pp:+8.2f} "
            f"{comparison.planning_success_effect_pp:+9.2f} "
            f"{comparison.planning_permutation_p_holm:7.4f} "
            f"{comparison.localisation_effect_mm:+8.3f} "
            f"{comparison.sigma_effect_mm:+10.3f} "
            f"{comparison.movement_effect_mm:+9.3f} "
            f"{path_text}"
        )

    print()

    print(
        "Planning-success p-values above are Holm corrected "
        "across the complete secondary comparison family."
    )

    print()

    print(
        "The frozen primary conclusion is NOT replaced by "
        "any secondary result."
    )


def main() -> None:
    """Run secondary analysis on the existing held-out CSV."""

    parser = argparse.ArgumentParser(
        description=(
            "Analyse all frozen Phase 1 held-out strategies "
            "without rerunning simulation."
        )
    )

    parser.add_argument(
        "--input",
        type=str,
        default=(
            "results/"
            "phase1_held_out/"
            "held_out_raw_records.csv"
        ),
    )

    parser.add_argument(
        "--output",
        type=str,
        default=(
            "results/"
            "phase1_held_out/"
            "held_out_secondary_analysis.json"
        ),
    )

    args = parser.parse_args()

    analysis = (
        run_secondary_analysis(
            raw_path=(
                args.input
            ),
        )
    )

    print_secondary_analysis(
        analysis
    )

    output = (
        save_secondary_analysis(
            analysis,
            output_path=(
                args.output
            ),
            overwrite=False,
        )
    )

    print()

    print(
        f"Secondary evidence saved to: {output}"
    )


if __name__ == "__main__":
    main()