"""Perception-to-navigation integration for three-strategy experiments.

This module connects the common perception result produced by fixed-view,
generic active-perception and task-aware active-perception strategies to the
existing uncertainty-aware motion-planning framework.

Ground-truth anatomy remains separate from planner-facing perceived anatomy.
The planner receives only noisy anatomical estimates with uncertainty-inflated
safety margins.  The resulting trajectory is then evaluated independently
against hidden ground-truth geometry.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from src.geometry.workspace import SphericalStructure
from src.perception.planning import (
    PlanningPerception,
    maximum_planning_safety_radius,
    mean_planning_safety_margin,
    uncertainty_aware_planning_structures,
)
from src.robotics.instrument import SurgicalInstrument
from src.simulation.three_strategy_perception import (
    StrategyPerceptionResult,
)
from src.simulation.uncertainty_benchmark import (
    TrialResult,
    run_planner_trial,
)


@dataclass(frozen=True)
class StrategyNavigationResult:
    """Combined perception and motion-planning result for one strategy."""

    trial: int
    perception: StrategyPerceptionResult
    planning_perception: PlanningPerception
    planner_result: TrialResult

    sigma_multiplier: float

    mean_planning_safety_margin: float
    maximum_planning_safety_radius: float

    @property
    def strategy(self) -> str:
        """Return the strategy identifier."""

        return self.perception.strategy.value

    @property
    def planning_success(self) -> bool:
        """Return whether motion planning succeeded."""

        return self.planner_result.planning_success

    @property
    def collision_against_truth(self) -> bool:
        """Return whether the final trajectory collided with hidden truth."""

        return self.planner_result.collision_against_truth

    @property
    def safety_violation_against_truth(self) -> bool:
        """Return whether the trajectory violated the true safety margin."""

        return self.planner_result.safety_violation_against_truth

    @property
    def minimum_true_safety_clearance(self) -> float:
        """Return minimum trajectory clearance to hidden ground truth."""

        return self.planner_result.minimum_true_safety_clearance


def build_uncertainty_aware_planning_perception(
    *,
    perception: StrategyPerceptionResult,
    sigma_multiplier: float,
) -> PlanningPerception:
    """Convert one strategy's perception into planner-facing geometry.

    The safety margin around every perceived anatomical structure is inflated
    according to:

        planning_margin
        =
        base_margin
        +
        sigma_multiplier * principal_sigma

    Parameters
    ----------
    perception:
        Common perception output generated by one of the three strategies.

    sigma_multiplier:
        Number of positional standard deviations added to each anatomical
        safety margin.

    Returns
    -------
    PlanningPerception
        Uncertainty-aware geometry suitable for the motion planner.
    """

    sigma_multiplier = float(
        sigma_multiplier
    )

    if not np.isfinite(
        sigma_multiplier
    ):
        raise ValueError(
            "sigma_multiplier must be finite."
        )

    if sigma_multiplier < 0.0:
        raise ValueError(
            "sigma_multiplier must be non-negative."
        )

    if (
        len(
            perception
            .perception_result
            .estimated_structures
        )
        == 0
    ):
        raise ValueError(
            "perception must contain at least one "
            "estimated structure."
        )

    return uncertainty_aware_planning_structures(
        perception_result=(
            perception.perception_result
        ),
        sigma_multiplier=sigma_multiplier,
    )


def run_navigation_from_perception(
    *,
    trial: int,
    perception: StrategyPerceptionResult,
    instrument: SurgicalInstrument,
    start_q: np.ndarray,
    goal_q: np.ndarray,
    true_structures: tuple[SphericalStructure, ...],
    sigma_multiplier: float,
    instrument_radius: float,
    proximal_length: float,
    planner_seed: int,
) -> StrategyNavigationResult:
    """Plan using one strategy's uncertain anatomical estimate.

    The planner receives only the perceived anatomical structures after
    uncertainty inflation.  Hidden ground-truth structures are supplied only
    to the independent trajectory-evaluation stage performed by
    ``run_planner_trial``.

    Parameters
    ----------
    trial:
        Trial identifier used in experimental records.

    perception:
        Output from fixed, generic-active or task-aware-active perception.

    instrument:
        RCM-constrained surgical instrument.

    start_q:
        Initial four-dimensional joint configuration.

    goal_q:
        Goal four-dimensional joint configuration.

    true_structures:
        Hidden ground-truth anatomy used for evaluation only.

    sigma_multiplier:
        Number of uncertainty standard deviations used to inflate the
        planner safety margin.

    instrument_radius:
        Physical radius of the simulated instrument shaft.

    proximal_length:
        Length of shaft represented proximally from the RCM.

    planner_seed:
        Random seed supplied to the RRT planner.

    Returns
    -------
    StrategyNavigationResult
        Combined perception, planner geometry and ground-truth navigation
        result.
    """

    if trial < 0:
        raise ValueError(
            "trial must be non-negative."
        )

    if len(true_structures) == 0:
        raise ValueError(
            "true_structures must contain at least one structure."
        )

    start_q = np.asarray(
        start_q,
        dtype=float,
    )

    goal_q = np.asarray(
        goal_q,
        dtype=float,
    )

    if start_q.shape != (4,):
        raise ValueError(
            "start_q must have shape (4,)."
        )

    if goal_q.shape != (4,):
        raise ValueError(
            "goal_q must have shape (4,)."
        )

    if instrument_radius <= 0.0:
        raise ValueError(
            "instrument_radius must be positive."
        )

    if proximal_length <= 0.0:
        raise ValueError(
            "proximal_length must be positive."
        )

    planning_perception = (
        build_uncertainty_aware_planning_perception(
            perception=perception,
            sigma_multiplier=sigma_multiplier,
        )
    )

    planner_result = run_planner_trial(
        trial=trial,
        method=perception.strategy.value,
        instrument=instrument,
        start_q=start_q,
        goal_q=goal_q,
        planning_structures=(
            planning_perception.structures
        ),
        true_structures=true_structures,
        instrument_radius=instrument_radius,
        proximal_length=proximal_length,
        planner_seed=planner_seed,
    )

    return StrategyNavigationResult(
        trial=int(trial),
        perception=perception,
        planning_perception=planning_perception,
        planner_result=planner_result,
        sigma_multiplier=float(
            sigma_multiplier
        ),
        mean_planning_safety_margin=(
            mean_planning_safety_margin(
                planning_perception
            )
        ),
        maximum_planning_safety_radius=(
            maximum_planning_safety_radius(
                planning_perception
            )
        ),
    )