"""Lightweight learned segmentation for Phase 4.

This module provides:

- a compact U-Net-style binary segmentation network;
- NumPy-to-PyTorch dataset adaptation;
- combined BCE + soft-Dice loss;
- binary segmentation metrics;
- centroid extraction from learned masks;
- deterministic training and evaluation utilities.

The network operates on synthetic engineering images generated by the
Phase 4 dataset. It is not a clinically validated tissue-segmentation model.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import torch
from torch import nn
from torch.utils.data import (
    DataLoader,
    Dataset,
)

from src.perception.ml_dataset import (
    SyntheticSegmentationDataset,
)


class DoubleConv(nn.Module):
    """Two convolution, normalisation and ReLU operations."""

    def __init__(
        self,
        in_channels: int,
        out_channels: int,
    ) -> None:
        super().__init__()

        self.block = nn.Sequential(
            nn.Conv2d(
                in_channels,
                out_channels,
                kernel_size=3,
                padding=1,
                bias=False,
            ),
            nn.BatchNorm2d(
                out_channels
            ),
            nn.ReLU(
                inplace=True
            ),
            nn.Conv2d(
                out_channels,
                out_channels,
                kernel_size=3,
                padding=1,
                bias=False,
            ),
            nn.BatchNorm2d(
                out_channels
            ),
            nn.ReLU(
                inplace=True
            ),
        )

    def forward(
        self,
        x: torch.Tensor,
    ) -> torch.Tensor:
        return self.block(
            x
        )


class TinyUNet(nn.Module):
    """Small U-Net suitable for CPU-based synthetic experiments."""

    def __init__(
        self,
        base_channels: int = 8,
    ) -> None:
        super().__init__()

        if base_channels < 2:
            raise ValueError(
                "base_channels must be at least 2."
            )

        self.encoder1 = DoubleConv(
            3,
            base_channels,
        )

        self.pool1 = nn.MaxPool2d(
            kernel_size=2
        )

        self.encoder2 = DoubleConv(
            base_channels,
            2 * base_channels,
        )

        self.pool2 = nn.MaxPool2d(
            kernel_size=2
        )

        self.bottleneck = DoubleConv(
            2 * base_channels,
            4 * base_channels,
        )

        self.up2 = nn.ConvTranspose2d(
            4 * base_channels,
            2 * base_channels,
            kernel_size=2,
            stride=2,
        )

        self.decoder2 = DoubleConv(
            4 * base_channels,
            2 * base_channels,
        )

        self.up1 = nn.ConvTranspose2d(
            2 * base_channels,
            base_channels,
            kernel_size=2,
            stride=2,
        )

        self.decoder1 = DoubleConv(
            2 * base_channels,
            base_channels,
        )

        self.output = nn.Conv2d(
            base_channels,
            1,
            kernel_size=1,
        )

    def forward(
        self,
        x: torch.Tensor,
    ) -> torch.Tensor:
        if (
            x.ndim != 4
            or x.shape[1] != 3
        ):
            raise ValueError(
                "Input must have shape (N, 3, H, W)."
            )

        if (
            x.shape[2] % 4 != 0
            or x.shape[3] % 4 != 0
        ):
            raise ValueError(
                "Image height and width must be divisible by 4."
            )

        encoder1 = (
            self.encoder1(
                x
            )
        )

        encoder2 = (
            self.encoder2(
                self.pool1(
                    encoder1
                )
            )
        )

        bottleneck = (
            self.bottleneck(
                self.pool2(
                    encoder2
                )
            )
        )

        decoder2 = self.up2(
            bottleneck
        )

        decoder2 = torch.cat(
            (
                decoder2,
                encoder2,
            ),
            dim=1,
        )

        decoder2 = (
            self.decoder2(
                decoder2
            )
        )

        decoder1 = self.up1(
            decoder2
        )

        decoder1 = torch.cat(
            (
                decoder1,
                encoder1,
            ),
            dim=1,
        )

        decoder1 = (
            self.decoder1(
                decoder1
            )
        )

        return self.output(
            decoder1
        )


class TorchSegmentationDataset(
    Dataset,
):
    """PyTorch adapter around the leakage-safe NumPy dataset."""

    def __init__(
        self,
        dataset: SyntheticSegmentationDataset,
    ) -> None:
        self.dataset = dataset

    def __len__(
        self,
    ) -> int:
        return (
            self.dataset.sample_count
        )

    def __getitem__(
        self,
        index: int,
    ) -> tuple[
        torch.Tensor,
        torch.Tensor,
    ]:
        image_bgr = (
            self.dataset.images[
                index
            ]
        )

        # Convert BGR -> RGB and make memory contiguous.
        image_rgb = (
            image_bgr[
                :,
                :,
                ::-1
            ]
            .copy()
        )

        image = (
            torch.from_numpy(
                image_rgb
            )
            .permute(
                2,
                0,
                1,
            )
            .float()
            / 255.0
        )

        mask = (
            torch.from_numpy(
                self.dataset.masks[
                    index
                ]
            )
            .float()
            .unsqueeze(
                0
            )
            / 255.0
        )

        return (
            image,
            mask,
        )


def soft_dice_loss(
    logits: torch.Tensor,
    targets: torch.Tensor,
    epsilon: float = 1e-6,
) -> torch.Tensor:
    """Differentiable Dice loss for binary segmentation."""

    if logits.shape != targets.shape:
        raise ValueError(
            "logits and targets must have identical shapes."
        )

    probabilities = (
        torch.sigmoid(
            logits
        )
    )

    dimensions = tuple(
        range(
            1,
            logits.ndim,
        )
    )

    intersection = torch.sum(
        probabilities
        * targets,
        dim=dimensions,
    )

    denominator = (
        torch.sum(
            probabilities,
            dim=dimensions,
        )
        + torch.sum(
            targets,
            dim=dimensions,
        )
    )

    dice = (
        2.0
        * intersection
        + epsilon
    ) / (
        denominator
        + epsilon
    )

    return (
        1.0
        - torch.mean(
            dice
        )
    )


def combined_segmentation_loss(
    logits: torch.Tensor,
    targets: torch.Tensor,
    *,
    positive_weight: float = 8.0,
) -> torch.Tensor:
    """Combine weighted BCE and Dice losses."""

    if positive_weight <= 0.0:
        raise ValueError(
            "positive_weight must be positive."
        )

    positive_weight_tensor = torch.tensor(
        positive_weight,
        dtype=logits.dtype,
        device=logits.device,
    )

    bce = nn.functional.binary_cross_entropy_with_logits(
        logits,
        targets,
        pos_weight=(
            positive_weight_tensor
        ),
    )

    dice = soft_dice_loss(
        logits,
        targets,
    )

    return (
        0.5
        * bce
        + 0.5
        * dice
    )


@dataclass(frozen=True)
class SegmentationMetrics:
    """Aggregate learned-segmentation metrics."""

    dice: float

    iou: float

    pixel_accuracy: float

    detection_rate: float

    mean_centroid_error_pixels: float


def binary_segmentation_metrics(
    predicted_mask: np.ndarray,
    true_mask: np.ndarray,
) -> tuple[
    float,
    float,
    float,
]:
    """Return Dice, IoU and pixel accuracy for two binary masks."""

    predicted = np.asarray(
        predicted_mask,
        dtype=bool,
    )

    truth = np.asarray(
        true_mask,
        dtype=bool,
    )

    if predicted.shape != truth.shape:
        raise ValueError(
            "predicted_mask and true_mask must have identical shapes."
        )

    intersection = int(
        np.count_nonzero(
            predicted
            & truth
        )
    )

    predicted_count = int(
        np.count_nonzero(
            predicted
        )
    )

    truth_count = int(
        np.count_nonzero(
            truth
        )
    )

    union = int(
        np.count_nonzero(
            predicted
            | truth
        )
    )

    if (
        predicted_count
        + truth_count
        == 0
    ):
        dice = 1.0
    else:
        dice = (
            2.0
            * intersection
            / (
                predicted_count
                + truth_count
            )
        )

    if union == 0:
        iou = 1.0
    else:
        iou = (
            intersection
            / union
        )

    accuracy = float(
        np.mean(
            predicted
            == truth
        )
    )

    return (
        float(
            dice
        ),
        float(
            iou
        ),
        accuracy,
    )


def binary_mask_centroid(
    mask: np.ndarray,
) -> np.ndarray | None:
    """Return [u, v] centroid of a binary foreground mask."""

    mask = np.asarray(
        mask,
        dtype=bool,
    )

    if mask.ndim != 2:
        raise ValueError(
            "mask must be two-dimensional."
        )

    rows, columns = np.nonzero(
        mask
    )

    if rows.size == 0:
        return None

    return np.asarray(
        [
            float(
                np.mean(
                    columns
                )
            ),
            float(
                np.mean(
                    rows
                )
            ),
        ],
        dtype=float,
    )


def evaluate_segmentation_model(
    *,
    model: nn.Module,
    dataset: SyntheticSegmentationDataset,
    device: torch.device,
    batch_size: int = 16,
    threshold: float = 0.5,
) -> SegmentationMetrics:
    """Evaluate one learned model without modifying it."""

    if not (
        0.0
        < threshold
        < 1.0
    ):
        raise ValueError(
            "threshold must lie between 0 and 1."
        )

    loader = DataLoader(
        TorchSegmentationDataset(
            dataset
        ),
        batch_size=batch_size,
        shuffle=False,
    )

    model.eval()

    dice_values: list[
        float
    ] = []

    iou_values: list[
        float
    ] = []

    accuracy_values: list[
        float
    ] = []

    centroid_errors: list[
        float
    ] = []

    detection_count = 0

    sample_index = 0

    with torch.no_grad():
        for images, targets in loader:
            images = images.to(
                device
            )

            logits = model(
                images
            )

            probabilities = (
                torch.sigmoid(
                    logits
                )
            )

            predictions = (
                probabilities
                >= threshold
            )

            predictions_np = (
                predictions
                .cpu()
                .numpy()
            )

            targets_np = (
                targets
                .numpy()
                >= 0.5
            )

            for local_index in range(
                predictions_np.shape[
                    0
                ]
            ):
                predicted = (
                    predictions_np[
                        local_index,
                        0,
                    ]
                )

                truth = (
                    targets_np[
                        local_index,
                        0,
                    ]
                )

                (
                    dice,
                    iou,
                    accuracy,
                ) = binary_segmentation_metrics(
                    predicted,
                    truth,
                )

                dice_values.append(
                    dice
                )

                iou_values.append(
                    iou
                )

                accuracy_values.append(
                    accuracy
                )

                centroid = (
                    binary_mask_centroid(
                        predicted
                    )
                )

                if centroid is not None:
                    detection_count += 1

                    expected = (
                        dataset
                        .marker_pixels[
                            sample_index
                        ]
                    )

                    centroid_errors.append(
                        float(
                            np.linalg.norm(
                                centroid
                                - expected
                            )
                        )
                    )

                sample_index += 1

    if centroid_errors:
        mean_centroid_error = float(
            np.mean(
                centroid_errors
            )
        )
    else:
        mean_centroid_error = float(
            "inf"
        )

    return SegmentationMetrics(
        dice=float(
            np.mean(
                dice_values
            )
        ),
        iou=float(
            np.mean(
                iou_values
            )
        ),
        pixel_accuracy=float(
            np.mean(
                accuracy_values
            )
        ),
        detection_rate=float(
            detection_count
            / dataset.sample_count
        ),
        mean_centroid_error_pixels=(
            mean_centroid_error
        ),
    )